# Generated by Django 3.0.7 on 2020-06-16 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id_bank', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id_bill', models.AutoField(primary_key=True, serialize=False)),
                ('total_bs', models.FloatField()),
                ('points', models.IntegerField()),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('id_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('F', 'Femenine'), ('M', 'Masculine')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id_store', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('max_capacity', models.IntegerField()),
                ('openingHour', models.TimeField()),
                ('closingHour', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='id_category',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='models.Client')),
                ('name', models.CharField(max_length=30, null=True)),
                ('identification', models.CharField(max_length=8, unique=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id_warehouse', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('max_capacity', models.IntegerField()),
                ('id_store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Stored_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Product')),
                ('id_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shelf', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Product')),
                ('id_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Store')),
            ],
            options={
                'unique_together': {('id_store', 'id_shelf')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Category'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('identification', models.CharField(max_length=8, unique=True)),
                ('salary', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Femenine'), ('M', 'Masculine')], max_length=1)),
                ('id_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Bill')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Product')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='id_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Store'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Client')),
                ('id_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Store')),
            ],
            options={
                'unique_together': {('id_client', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='Shelf_Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('id_shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Shelf')),
                ('id_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Store')),
            ],
            options={
                'unique_together': {('id_store', 'id_shelf')},
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.IntegerField()),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Product')),
            ],
            options={
                'unique_together': {('id_product', 'date')},
            },
        ),
    ]
